server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://127.0.0.1:8090/message
          predicates:
            - Path=/message/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000